{{- if .Values.sns.forwarder.email.enabled  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager-sns-forwarder.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "alertmanager-sns-forwarder.name" . }}
    helm.sh/chart: {{ include "alertmanager-sns-forwarder.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ include "alertmanager-sns-forwarder.name" . }}
type: Opaque
data:
  email.tmpl: {{ .Files.Get .Values.sns.forwarder.email.templateFilePath | b64enc }}
{{- end }}